# Getting Started

First, import the `bdikit` library.

In [2]:
import bdikit as bdi
import pandas as pd

In this example, we are mapping data from Dou et al. (https://pubmed.ncbi.nlm.nih.gov/37567170/) to the GDC format.

In [3]:
dataset = pd.read_csv("./datasets/Huang.csv")

# columns = [
#     "Country",
#     "Histologic_type",
#     "FIGO_stage",
#     "BMI",
#     "Age",
#     "Race",
#     "Ethnicity",
#     "Gender",
#     "Tumor_Focality",
#     "Tumor_Size_cm",
# ]

# dataset[columns].head(10)
dataset.head(10)

,case_id,age,gender,country,smoking_history,smoke_age_start,smoke_age_stop,num_smoke_per_day,num_pack_years_sm,smoking_second_hand,...,tumor_pathology_review,ESTIMATE_stromal_score,ESTIMATE_immune_score,CD3_IHC_count,stemness_score,mutation_count,neoAntigen_count,chr_instability_idx,integrated_subtype,transcriptomic_subtype
0,C3L-00977,56,Male,Russia,"Current reformed smoker, years unknown",NaN,NaN,20,NaN,Yes,...,SCC 80%,6825.995755,7989.115925,1.0,0.953243,106,0,2.003654,Basal,Mesenchymal
1,C3L-00987,61,Male,Ukraine,Current smoker: Includes daily and non-daily s...,18,NaN,20,43.0,Yes,...,SCC 90%;SCC 90%;SCC 80%;SCC 70%,5999.793467,4772.409716,0.0,0.825330,83,0,5.205612,CIN,Classical
2,C3L-00994,50,Male,Ukraine,Current reformed smoker within past 15 years,16,50,6,10.2,Exposure to secondhand smoke history not avail...,...,SCC 40%;SCC 70%;SCC 40%;SCC 75%,8924.036564,8176.233903,5.0,0.664581,67,0,1.684475,Immune,Mesenchymal
3,C3L-00995,56,Male,Ukraine,"Current reformed smoker, more than 15 years",25,56,20,31.0,Exposure to secondhand smoke history not avail...,...,SCC 90%;SCC 80%;SCC 40%;SCC 70%,8723.429667,8342.246345,70.0,0.539918,64,0,1.340483,Immune,Mesenchymal
4,C3L-00997,47,Male,Ukraine,"Current reformed smoker, more than 15 years",12,27,20,15.0,Yes,...,SCC 70%;SCC 70%,7025.911695,7445.251991,60.0,0.843765,129,0,3.906370,CIN,Classical
5,C3L-00999,56,Male,Russia,Current smoker: Includes daily and non-daily s...,20,NaN,20,36.0,Yes,...,SCC 80%;SCC 70%,8510.704551,8210.549555,30.0,0.548977,159,0,1.148834,Immune,Atypical
6,C3L-01138,62,Male,Ukraine,Current smoker: Includes daily and non-daily s...,8,NaN,20,54.0,Exposure to secondhand smoke history not avail...,...,SCC 70%,6283.423855,6407.893478,10.0,0.890790,187,1,3.924982,Basal,Classical
7,C3L-01237,57,Male,Ukraine,"Current reformed smoker, more than 15 years",17,20,40,6.0,Exposure to secondhand smoke history not avail...,...,SCC 80%,7175.667725,5720.287055,30.0,0.738328,141,1,4.286490,CIN,Classical
8,C3L-02617,64,Male,Bulgaria,Current smoker: Includes daily and non-daily s...,20,NaN,30,66.0,Yes,...,SCC 90%;SCC 80%;SCC 80%;SCC 80%;SCC 80%,6346.815584,6958.573390,NaN,0.906466,470,1,4.744818,CIN,Classical
9,C3L-02621,68,Male,Bulgaria,Current smoker: Includes daily and non-daily s...,38,NaN,30,45.0,Yes,...,SCC 70%;SCC 70%;SCC 70%;SCC 70%;SCC 65%,6806.384264,8039.787184,NaN,0.754950,358,0,1.774521,CIN,Atypical

### Matching the table schema to GDC standard vocabulary

`bdi-kit` offers a suite of functions to help with data harmonization tasks.
For instance, it can help with automatic discovery of one-to-one mappings between the columns in the input (source) dataset and a target dataset schema. The target schema can be either another table or a standard data vocabulary such as the GDC (Genomic Data Commons).

To achieve this using `bdi-kit`, we can use the `match_schema()` function to match columns to the GDC vocabulary schema as follows.

In [6]:
column_mappings = bdi.match_schema(dataset, target="gdc", method="ct_learning")
column_mappings

Extracting features from 37 columns...

  0%|          | 0/37 [00:00<?, ?it/s]

Table features loaded for 734 columns

                       source                            target
0                     case_id                 catalog_reference
1                         age                      age_at_onset
2                      gender                            gender
3                     country                  country_of_birth
4             smoking_history            tobacco_smoking_status
5             smoke_age_start                      years_smoked
6              smoke_age_stop                      years_smoked
7           num_smoke_per_day                      years_smoked
8           num_pack_years_sm                 pack_years_smoked
9         smoking_second_hand                   relative_smoker
10           smoking_inferred                   relative_smoker
11             alcohol_consum                 alcohol_intensity
12            num_yrs_alc_con  undescended_testis_corrected_age
13        tumor_site_original                      primary_site
14         tumor_site_curated            tumor_depth_descriptor
15             tumor_focality                    tumor_focality
16              tumor_size_cm           tumor_width_measurement
17            histologic_type                             roots
18           histologic_grade                     who_nte_grade
19             tumor_necrosis                  necrosis_present
20           patho_staging_pt                ensat_pathologic_t
21           patho_staging_pn                 ajcc_pathologic_n
22  clinic_staging_dist_metas                   uicc_clinical_m
23                tumor_stage            ensat_pathologic_stage
24                        P16                  scan_tracer_used
25              HPV_inference         vascular_invasion_present
26       NAT_pathology_review          staining_intensity_scale
27     tumor_pathology_review             best_overall_response
28     ESTIMATE_stromal_score                        transcript
29      ESTIMATE_immune_score                        transcript
30              CD3_IHC_count                         cd4_count
31             stemness_score                        transcript
32             mutation_count                    mutation_codon
33           neoAntigen_count                ensat_pathologic_n
34        chr_instability_idx                        transcript
35         integrated_subtype                             roots
36     transcriptomic_subtype               fab_morphology_code

### Generating a harmonized table

After discovering a schema mapping, we can generate a new table (DataFrame) using the new column names from the GDC standard vocabulary.

To do so using `bdi-kit`, we can use the function `materialize_mapping()` as follows. Note that the column headers have been renamed to the target schema.

In [4]:
bdi.materialize_mapping(dataset, column_mappings)

,country_of_birth,dysplasia_type,figo_stage,hpv_positive_type,weight,race,ethnicity,gender,tumor_focality,tumor_depth
0,United States,Endometrioid,IA,38.88,64.0,White,Not-Hispanic or Latino,Female,Unifocal,2.9
1,United States,Endometrioid,IA,39.76,58.0,White,Not-Hispanic or Latino,Female,Unifocal,3.5
2,United States,Endometrioid,IA,51.19,50.0,White,Not-Hispanic or Latino,Female,Unifocal,4.5
3,NaN,Carcinosarcoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,Endometrioid,IA,32.69,75.0,White,Not-Hispanic or Latino,Female,Unifocal,3.5
...,...,...,...,...,...,...,...,...,...,...
99,Ukraine,Endometrioid,IA,29.40,75.0,NaN,NaN,Female,Unifocal,4.2
100,Ukraine,Endometrioid,II,35.42,74.0,NaN,NaN,Female,Unifocal,1.5
101,United States,Serous,II,24.32,85.0,Black or African American,Not-Hispanic or Latino,Female,Unifocal,3.8
102,Ukraine,Serous,IA,34.06,70.0,NaN,NaN,Female,Unifocal,5.0
103,Ukraine,Serous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Generating a harmonized table with value mappings

`bdi-kit` can also help with translation of the values from the source table to the target standard format.

To this end, `bdi-kit` provides the function `match_values()` that automatically creates value mappings for each string column.
The output of `match_values()` can be fed to `materialize_mapping()` which materialized the final target using both schema and value mappings.

In [5]:
value_mappings = bdi.match_values(dataset, column_mapping=column_mappings, target="gdc", method="tfidf")
bdi.materialize_mapping(dataset, value_mappings)

,country_of_birth,dysplasia_type,figo_stage,race,ethnicity,gender,tumor_focality
0,United States,None,Stage IA,white,not hispanic or latino,female,Unifocal
1,United States,None,Stage IA,white,not hispanic or latino,female,Unifocal
2,United States,None,Stage IA,white,not hispanic or latino,female,Unifocal
3,NaN,Esophageal Mucosa Columnar Dysplasia,NaN,NaN,NaN,NaN,NaN
4,United States,None,Stage IA,white,not hispanic or latino,female,Unifocal
...,...,...,...,...,...,...,...
99,Ukraine,None,Stage IA,NaN,NaN,female,Unifocal
100,Ukraine,None,Stage III,NaN,NaN,female,Unifocal
101,United States,None,Stage III,black or african american,not hispanic or latino,female,Unifocal
102,Ukraine,None,Stage IA,NaN,NaN,female,Unifocal
103,Ukraine,None,NaN,NaN,NaN,NaN,NaN

### Verifying the schema mappings

Sometimes the mappings generated automatically may be incorrect or you may to want verify them individually.
To verify the suggested column mappings, `bdi-kit` offers additional APIs to visualize the data and make any modifications when necessary. 

For this example, we will use the column `Histologic_type`. We can start by exploring the columns most similar to `Histologic_type`. 

For this, we can use the `top_matches()` function. Here, we notice that `primary_diagnosis` could be a potential target column.

In [6]:
hist_type_matches = bdi.top_matches(dataset, columns=["Histologic_type"], target="gdc")
hist_type_matches

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
100%|██████████| 1/1 [00:00<00:00, 14.70it/s]

Table features extracted from 1 columns

100%|██████████| 734/734 [00:58<00:00, 12.48it/s]

Table features extracted from 734 columns

            source                          target  similarity
0  Histologic_type                 described_cases    0.589956
1  Histologic_type                    slide_images    0.587552
2  Histologic_type           history_of_tumor_type    0.574640
3  Histologic_type               primary_diagnosis    0.573583
4  Histologic_type   additional_pathology_findings    0.562278
5  Histologic_type               pathology_details    0.562007
6  Histologic_type               pathology_reports    0.547307
7  Histologic_type  relationship_primary_diagnosis    0.524285
8  Histologic_type                       diagnoses    0.519854
9  Histologic_type                family_histories    0.516649

### Viewing the column domains

To verify that `primary_diagnosis` is a good target column, we view and compare the domains of each column using the `preview_domain()` function. For the source table, it returns the list of unique values in the source column. For the GDC target, it returns the list of unique valid values that a column can have.

Here we see that the values seem to be related.

In [7]:
bdi.preview_domain(dataset, "Histologic_type")

       value_name
0    Endometrioid
1  Carcinosarcoma
2          Serous
3      Clear cell

In [8]:
bdi.preview_domain("gdc", "primary_diagnosis")

,value_name,value_description,column_description
0,Abdominal desmoid,An insidious poorly circumscribed neoplasm ari...,Text term used to describe the patient's histo...
1,Abdominal fibromatosis,An insidious poorly circumscribed neoplasm ari...,
2,Achromic nevus,A benign nevus characterized by the absence of...,
3,Acidophil adenocarcinoma,A malignant epithelial neoplasm of the anterio...,
4,Acidophil adenoma,An epithelial neoplasm of the anterior pituita...,
...,...,...,...
2620,Wolffian duct tumor,An epithelial neoplasm of the female reproduct...,
2621,Xanthofibroma,A benign neoplasm composed of fibroblastic spi...,
2622,Yolk sac tumor,A non-seminomatous malignant germ cell tumor c...,
2623,Unknown,"Not known, not observed, not recorded, or refu...",
2624,Not Reported,Not provided or available.,

Since `primary_diagnosis` looks like a correct match for `Histologic_type`, we can modify the `column_mappings` variable directly.

In [8]:
column_mappings.loc[column_mappings["source"] == "Histologic_type", "target"] = "primary_diagnosis"
column_mappings

            source             target
0          Country   country_of_birth
1  Histologic_type  primary_diagnosis
2       FIGO_stage         figo_stage
3              BMI  hpv_positive_type
4              Age             weight
5             Race               race
6        Ethnicity          ethnicity
7           Gender             gender
8   Tumor_Focality     tumor_focality
9    Tumor_Size_cm        tumor_depth

### Finding correct value mappings

After finding the correct column, we need to find appropriate value mappings. 
Using `match_values()`, we can inspect what the possible value mappings for this would look like after the harmonization.

`bdi-kit` implements multiple methods for value mapping discovery, including:

 - `edit_distance` - Computes value similarities using Levenstein's edit distance measure.
 - `tfidf` - A method based on tf-idf importance weighting computed over charcter n-grams.
 - `embeddings` - Uses BERT word embeddings to compute "semantic similarity" between the values.

To specify a value mapping approach, we can pass the `method` parameter.

In [9]:
bdi.match_values(
    dataset, column_mapping=("Histologic_type", "primary_diagnosis"), target="gdc", method="edit_distance"
)

           source                 target  similarity
0  Carcinosarcoma    Carcinosarcoma, NOS    0.848485
1      Clear cell     Clear cell adenoma    0.714286
2    Endometrioid  Stromal endometriosis    0.666667
3          Serous             Neuronevus    0.625000

In [10]:
bdi.match_values(
    dataset, column_mapping=("Histologic_type", "primary_diagnosis"), target="gdc", method="tfidf"
)

           source                     target  similarity
0  Carcinosarcoma        Carcinosarcoma, NOS       0.969
1    Endometrioid  Endometrioid adenoma, NOS       0.897
2      Clear cell         Clear cell adenoma       0.853
3          Serous      Serous carcinoma, NOS       0.755

In [11]:
bdi.match_values(
    dataset, column_mapping=("Histologic_type", "primary_diagnosis"), target="gdc", method="embedding"
)

           source                           target  similarity
0  Carcinosarcoma                   Carcinofibroma       0.919
1    Endometrioid  Endometrioid cystadenocarcinoma       0.810
2      Clear cell             Clear cell carcinoma       0.760
3          Serous                   Serous cystoma       0.661

In [12]:
hist_type_vmap = pd.DataFrame(
    columns=["source", "target"],
    data=[
        ("Carcinosarcoma", "Carcinosarcoma, NOS"),
        ("Clear cell", "Clear cell adenocarcinoma, NOS"),
        ("Endometrioid", "Endometrioid carcinoma"),
        ("Serous", "Serous cystadenocarcinoma"),
    ],
)
hist_type_vmap

           source                          target
0  Carcinosarcoma             Carcinosarcoma, NOS
1      Clear cell  Clear cell adenocarcinoma, NOS
2    Endometrioid          Endometrioid carcinoma
3          Serous       Serous cystadenocarcinoma

### Verifying multiple value mappings at once

Besides verifying value mappings individually, you can also do it for all column mappings at once.

In [7]:
mappings = bdi.match_values(
    dataset,
    column_mapping=column_mappings,
    target="gdc",
    method="tfidf",
)

for mapping in mappings:
    print(f"{mapping.attrs['source']} => {mapping.attrs['target']}")
    display(mapping)
    print("")

gender => gender

   source  target  similarity
0    Male    male         1.0
1  Female  female         1.0

country => country_of_birth

                source         target  similarity
0               Russia         Russia         1.0
1              Ukraine        Ukraine         1.0
2             Bulgaria       Bulgaria         1.0
3               Poland         Poland         1.0
4        United States  United States         1.0
5                China          China         1.0
6              Armenia        Armenia         1.0
7  TSS did not collect           None         NaN

smoking_history => tobacco_smoking_status

,source,target,similarity
0,"Current reformed smoker, more than 15 years",Current Reformed Smoker for > 15 yrs,0.823
1,"Current reformed smoker, years unknown",Current Reformed Smoker for > 15 yrs,0.756
2,Current reformed smoker within past 15 years,Current Reformed Smoker for > 15 yrs,0.719
3,Lifelong non-smoker: Less than 100 cigarettes ...,Lifelong Non-Smoker,0.697
4,Smoking history not available,Smoking history not documented,0.564
5,Current smoker: Includes daily and non-daily s...,Current Smoker,0.506

smoking_second_hand => relative_smoker

                                              source        target  similarity
0                                                Yes           Yes       1.000
1         No or minimal exposure to secondhand smoke            No       0.410
2  Exposure to secondhand smoke history not avail...  Not Reported       0.352

smoking_inferred => relative_smoker

            source target similarity
0    weak_evidence   None       None
1  strong_evidence   None       None

alcohol_consum => alcohol_intensity

,source,target,similarity
0,Lifelong non-drinker,Lifelong Non-Drinker,1.000
1,"Consumed alcohol in the past, but currently a ...",Non-Drinker,0.437
2,Alcohol consumption more than 2 drinks per day...,Non-Drinker,0.370
3,Alcohol consumption equal to or less than 2 dr...,Occasional Drinker,0.360
4,Alcohol consumption history not available,None,NaN
5,nan,None,NaN

tumor_site_original => primary_site

,source,target,similarity
0,Floor of mouth,Floor of mouth,1.000
1,Larynx,Larynx,1.000
2,Oropharynx,Oropharynx,1.000
3,Base of tongue,Base of tongue,1.000
4,Lip,Lip,1.000
5,Tonsil,Tonsil,1.000
6,Tongue,Base of tongue,0.733
7,Oral cavity,"Other and ill-defined sites in lip, oral cavit...",0.542
8,Other,Other and unspecified parts of mouth,0.428
9,Alveolar ridge,None,NaN
10,Buccal mucosa,None,NaN

tumor_site_curated => tumor_depth_descriptor

        source target similarity
0          Lip   None       None
1   Oropharynx   None       None
2  Oral cavity   None       None
3  Hypopharynx   None       None
4       Larynx   None       None

tumor_focality => tumor_focality

       source      target  similarity
0    Unifocal    Unifocal         1.0
1  Multifocal  Multifocal         1.0

histologic_grade => who_nte_grade

                         source        target  similarity
0      G3 Poorly differentiated  Not Reported       0.431
1  G2 Moderately differentiated  Not Reported       0.358
2        G1 Well differentiated  Not Reported       0.310

tumor_necrosis => necrosis_present

           source target similarity
0  Not identified   None       None
1         Present   None       None

patho_staging_pt => ensat_pathologic_t

  source target  similarity
0     T2     T2       1.000
1    pT3     T3       0.703
2    pT1     T1       0.693
3    pT2     T2       0.661
4    pT4     T4       0.658
5    T4a     T4       0.567
6   pT4a     T4       0.476
7   pT1b     T1       0.475

patho_staging_pn => ajcc_pathologic_n

   source target  similarity
0     N3b    N3b       1.000
1      N1     N1       1.000
2    pN2c    N2c       0.828
3    pN3a    N3a       0.828
4    pN2b    N2b       0.819
5    pN3b    N3b       0.806
6     pNx     NX       0.706
7     pN2     N2       0.617
8     pN3     N3       0.617
9     pN0     N0       0.611
10    PN1     N1       0.534

clinic_staging_dist_metas => uicc_clinical_m

               source    target  similarity
0                  m0        M0       1.000
1                 cM0  cM0 (i+)       0.891
2                 cMX        MX       0.674
3  Staging Incomplete      None         NaN
4                 nan      None         NaN

tumor_stage => ensat_pathologic_stage

      source     target  similarity
0  Stage III  Stage III         1.0
1   Stage II   Stage II         1.0
2   Stage IV   Stage IV         1.0
3    Stage I    Stage I         1.0

P16 => scan_tracer_used

                                             source   target  similarity
0                                     Not Evaluated  Acetate       0.326
1  Positive (>70% nuclear and cytoplasmic staining)     None         NaN
2                                           Unknown     None         NaN
3                                          Negative     None         NaN
4                                               nan     None         NaN

HPV_inference => vascular_invasion_present

  source target  similarity
0     NO     No         1.0
1    YES    Yes         1.0

NAT_pathology_review => staining_intensity_scale

                                          source target similarity
0                                    Normal 60%%   None       None
1                         Normal 15%;Normal 10%%   None       None
2                                            nan   None       None
3                                    Normal 35%%   None       None
4                           Normal Cartilage 0%%   None       None
5                                    Normal 25%%   None       None
6                           Soft Tissue  No EPI%   None       None
7                                    Normal 20%%   None       None
8                                     Muscle 0%%   None       None
9                                    Normal 50%%   None       None
10             Normal 40%;Normal 20%;Normal 15%%   None       None
11                                        N 35%%   None       None
12                                         N 5%%   None       None
13                Normal EPI 10%;Normal EPI 10%%   None       None
14                               Normal 70$ EPI%   None       None
15  Normal Thyroid;Normal Thyroid;Normal No EPI%   None       None
16                                   Normal 40%%   None       None
17                                    Normal 5%%   None       None
18                                    Normal 1%%   None       None
19                           Normal 20%;SCC 75%%   None       None
20                              SCC 30%;SCC 20%%   None       None
21                                         N 3%%   None       None
22                                        N 25%%   None       None
23                             Normal Cartilage%   None       None
24                                Normal 0% EPI%   None       None
25                                        N 15%%   None       None
26            Soft Tissue  No EPI;Normal No EPI%   None       None
27           Normal 20%;Normal No EPI;Normal 5%%   None       None
28                                         N 0%%   None       None
29                                        N 20%%   None       None
30                               Normal 20% EPI%   None       None
31                         Normal 15%;Normal 5%%   None       None
32                                   Normal 30%%   None       None
33                                   Normal 10%%   None       None
34                              Hyperplasia 70%%   None       None
35                                 N lymphoid B%   None       None
36                                Normal no EPI%   None       None
37                                      SCC 75%%   None       None
38                Normal 10%;Normal 15%;SCC 90%%   None       None
39                                    Normal 0%%   None       None
40                                        N 10%%   None       None
41                                   Normal 15%%   None       None
42                                        N 30%%   None       None
43                SCC 70%;Normal 10%;Normal 30%%   None       None
44             Normal 10%;Normal 10%;Normal 10%%   None       None
45                                      SCC 70%%   None       None
46                                       Normal%   None       None

neoAntigen_count => ensat_pathologic_n

  source target  similarity
0      0     N0        0.54
1      1     N1        0.54
2      5   None         NaN
3      4   None         NaN
4      2   None         NaN
5      3   None         NaN

transcriptomic_subtype => fab_morphology_code

        source          target  similarity
0    Classical  Not Classified        0.53
1  Mesenchymal            None         NaN
2     Atypical            None         NaN
3        Basal            None         NaN

In [8]:
bdi.preview_domain("gdc", "who_nte_grade")

,value_name,value_description,column_description
0,G1,A morphologic qualifier indicating that a canc...,The WHO (World Health Organization) grading cl...
1,G2,A morphologic qualifier indicating that a canc...,
2,G3,A morphologic qualifier indicating that a canc...,
3,GX,A morphologic qualifier indicating that the gr...,
4,Unknown,,
5,Not Reported,Not provided or available.,

### Fixing remaining value mappings

We need fix a few value mappings:
- Race
- Ethnicity
- Tumor_Site

For race, we need to fix: `nan` -> `american indian or alaska native`.

In [14]:
race_vmap = bdi.match_values(
    dataset,
    column_mapping=("Race", "race"),
    target="gdc",
    method="tfidf",
)
race_vmap

                      source                            target  similarity
0                      White                             white       1.000
1                      Asian                             asian       1.000
2               Not Reported                      not reported       1.000
3  Black or African American         black or african american       1.000
4                        nan  american indian or alaska native       0.359

In [15]:
race_vmap = race_vmap[race_vmap["similarity"] >= 1.0]
race_vmap

                      source                     target  similarity
0                      White                      white         1.0
1                      Asian                      asian         1.0
2               Not Reported               not reported         1.0
3  Black or African American  black or african american         1.0

For `Ethnicity`, we need to fix: `Not reported` -> `not hispanic or latino`.

In [16]:
ethinicity_vmap = bdi.match_values(
    dataset,
    column_mapping=("Ethnicity", "ethnicity"),
    target="gdc",
    method="tfidf",
)
ethinicity_vmap

                   source                  target  similarity
0      Hispanic or Latino      hispanic or latino       1.000
1  Not-Hispanic or Latino  not hispanic or latino       0.935
2            Not reported  not hispanic or latino       0.268
3                     nan                    None         NaN

In [17]:
ethinicity_vmap = ethinicity_vmap[ethinicity_vmap["similarity"] > 0.9]
ethinicity_vmap

                   source                  target  similarity
0      Hispanic or Latino      hispanic or latino       1.000
1  Not-Hispanic or Latino  not hispanic or latino       0.935

For `Tumor_Site`, given that this dataset is about endometrial cancer, all values must be mapped to "Endometrium". So instead of fixing each mapping individually, we will write a custom function that returns "Endometrium" regardless of the input value. Later, we will show how to use this function to transform the dataset.

In [18]:
bdi.match_values(
    dataset, column_mapping=("Tumor_Site", "tissue_or_organ_of_origin"), target="gdc", method="tfidf"
)

                  source                             target  similarity
0   Anterior endometrium                        Endometrium       0.852
1  Posterior endometrium                        Endometrium       0.823
2         Other, specify  Other specified parts of pancreas       0.543
3                    nan                         Anal canal       0.301

In [19]:
# Custom mapping function that will be used to map the values of the 'Tumor_Site' column
def map_tumor_site(source_value):
    return "Endometrium"

### Combining custom user mappings with suggested mappings

Before generating a final harmonized dataset, we can combine the automatically generated value mappings with the fixed mappings provided by the user. To do so, we use `bdi.merge_mappings()` function, which take a list of mappings (e.g., generated automatically) and a list of "user-defined mapping overrides" that will be combined with the first list of mappings and will take precedence whenever they conflict.

In our example below, all mappings specified in the variable `user_mappings` will override the mappings in `value_mappings` generated by the `bdi.match_values()` function.

In [20]:
from math import ceil

user_mappings = [
    {
        # When no mapping is need, specifying the source and target is enough
        "source": "BMI",
        "target": "bmi",
    },
    {
        "source": "Tumor_Size_cm",
        "target": "tumor_largest_dimension_diameter",
    },
    {
        # mapper can be a custom Python function
        "source": "Tumor_Site",
        "target": "tissue_or_organ_of_origin",
        "mapper": map_tumor_site,
    },
    {
        # Lambda functions can also be used as mappers
        "source": "Age",
        "target": "days_to_birth",
        "mapper": lambda age: -age * 365.25,
    },
    {
        "source": "Age",
        "target": "age_at_diagnosis",
        "mapper": lambda age: float("nan") if pd.isnull(age) else ceil(age*365.25),
    },
    {
        # We can also use a data frame to specify value mappings using the `matches` attribute
        "source": "Histologic_type",
        "target": "primary_diagnosis",
        "matches": hist_type_vmap
    },
    # For dataframes that contain the 'source' and 'target' columns as attributes,
    # such as the ones returned by the match_values() function, we can directly
    # use them as mappings
    ethinicity_vmap,
    race_vmap,
]


harmonization_spec = bdi.merge_mappings(value_mappings, user_mappings)

Finally, we generate the harmonized dataset, with the user-defined value mappings.

In [21]:
harmonized_dataset = bdi.materialize_mapping(dataset, harmonization_spec)
harmonized_dataset

,tissue_or_organ_of_origin,bmi,days_to_birth,age_at_diagnosis,tumor_largest_dimension_diameter,country_of_birth,primary_diagnosis,figo_stage,race,ethnicity,gender,tumor_focality
0,Endometrium,38.88,-23376.00,23376.0,2.9,United States,"Endometrioid adenoma, NOS",Stage IA,white,not hispanic or latino,female,Unifocal
1,Endometrium,39.76,-21184.50,21185.0,3.5,United States,"Endometrioid adenoma, NOS",Stage IA,white,not hispanic or latino,female,Unifocal
2,Endometrium,51.19,-18262.50,18263.0,4.5,United States,"Endometrioid adenoma, NOS",Stage IA,white,not hispanic or latino,female,Unifocal
3,Endometrium,NaN,NaN,NaN,NaN,NaN,"Carcinosarcoma, NOS",NaN,NaN,NaN,NaN,NaN
4,Endometrium,32.69,-27393.75,27394.0,3.5,United States,"Endometrioid adenoma, NOS",Stage IA,white,not hispanic or latino,female,Unifocal
...,...,...,...,...,...,...,...,...,...,...,...,...
99,Endometrium,29.40,-27393.75,27394.0,4.2,Ukraine,"Endometrioid adenoma, NOS",Stage IA,NaN,NaN,female,Unifocal
100,Endometrium,35.42,-27028.50,27029.0,1.5,Ukraine,"Endometrioid adenoma, NOS",Stage III,NaN,NaN,female,Unifocal
101,Endometrium,24.32,-31046.25,31047.0,3.8,United States,"Serous carcinoma, NOS",Stage III,black or african american,not hispanic or latino,female,Unifocal
102,Endometrium,34.06,-25567.50,25568.0,5.0,Ukraine,"Serous carcinoma, NOS",Stage IA,NaN,NaN,female,Unifocal
103,Endometrium,NaN,NaN,NaN,NaN,Ukraine,"Serous carcinoma, NOS",NaN,NaN,NaN,NaN,NaN

For comparison, here is how our original data looked like:

In [22]:
original_columns = map(lambda m: m["source"], harmonization_spec)
dataset[original_columns]

,Tumor_Site,BMI,Age,Age,Tumor_Size_cm,Country,Histologic_type,FIGO_stage,Race,Ethnicity,Gender,Tumor_Focality
0,Anterior endometrium,38.88,64.0,64.0,2.9,United States,Endometrioid,IA,White,Not-Hispanic or Latino,Female,Unifocal
1,Posterior endometrium,39.76,58.0,58.0,3.5,United States,Endometrioid,IA,White,Not-Hispanic or Latino,Female,Unifocal
2,"Other, specify",51.19,50.0,50.0,4.5,United States,Endometrioid,IA,White,Not-Hispanic or Latino,Female,Unifocal
3,NaN,NaN,NaN,NaN,NaN,NaN,Carcinosarcoma,NaN,NaN,NaN,NaN,NaN
4,"Other, specify",32.69,75.0,75.0,3.5,United States,Endometrioid,IA,White,Not-Hispanic or Latino,Female,Unifocal
...,...,...,...,...,...,...,...,...,...,...,...,...
99,"Other, specify",29.40,75.0,75.0,4.2,Ukraine,Endometrioid,IA,NaN,NaN,Female,Unifocal
100,"Other, specify",35.42,74.0,74.0,1.5,Ukraine,Endometrioid,II,NaN,NaN,Female,Unifocal
101,"Other, specify",24.32,85.0,85.0,3.8,United States,Serous,II,Black or African American,Not-Hispanic or Latino,Female,Unifocal
102,"Other, specify",34.06,70.0,70.0,5.0,Ukraine,Serous,IA,NaN,NaN,Female,Unifocal
103,NaN,NaN,NaN,NaN,NaN,Ukraine,Serous,NaN,NaN,NaN,NaN,NaN